# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1856b5d13f62109c9c596f7d6df52c6217d98791297bcafdafb4a861175d4a2d3dd8e3a3f90220adaaad858d33338315dc38f7392e848dfe7d8e6225903bf74e

test:
  secret_key_base: fd96726529a015694bd57896ec5e8939518e7b1c7af7c6bfe9f81d5ce960ad326aafc24ef8e8a1b8c49ee8bfb4b851817a61f26f8214a7b992eab79e00e5956b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
